### ISSUE TITLE
How to test this implementation ?

### ISSUE THREAD

**Issue by X-Ryl669** [leonboe1/GoogleFindMyTools#1]
I'm wondering how to test this implementation (I don't have any BT tracker with Google's FindMy)?

What's missing ?

Can I help?

**Comment by leonboe1** [comment]
Hi there, testing without having trackers and rooted devices will be difficult.

The main thing missing currently is the communication with the server. If you want, you can try to take a look at the Find My Device APK to figure out how this process works.

**Comment by leonboe1** [comment]
You can now test everything Running main.py. If there is some issue, please open a new issue.
